# Generated by Django 6.1.1 on 2026-09-24 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Selected', 'Selected')], default='Applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='domain',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='qualification',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='opportunities', to='core.skill'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='type',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Job', 'Job'), ('Research', 'Research'), ('Workshop', 'Workshop')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Industry', 'Industry'), ('Academician', 'Academician'), ('Institution', 'Institution')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='domain',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.skill'),
        ),
    ]
